import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    paddingHorizontal: 14,
    paddingBottom: 16,
  },
  bg: { flex: 1 },
  bgImage: { opacity: 0.65 },
  bgOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  topBar: {
    paddingHorizontal: 4,
    paddingTop: 8,
    paddingBottom: 14,
    alignItems: "center",
    gap: 6,
  },
  topTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#f8f3eb",
    margin: 10,
  },
  topLogo: {
    width: 140,
    height: 46,
    resizeMode: "contain",
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#fdf8f0",
    textAlign: "center",
  },
  emptySubtitle: {
    marginTop: 6,
    color: "#f1e6d5",
    textAlign: "center",
  },
  listContent: {
    paddingBottom: 32,
    gap: 12,
  },
  card: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: "#fbf7f0",
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e6d7c7",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  productImg: {
    width: 72,
    height: 72,
    borderRadius: 12,
    backgroundColor: "#e8e0d6",
  },
  cardBody: { flex: 1, gap: 6 },
  cardHeaderRow: { flexDirection: "row", justifyContent: "space-between", gap: 8 },
  cardTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
    color: "#2c1b12",
  },
  cardCategory: {
    color: "#7a6858",
  },
  stockInfo: {
    color: "#8a3a30",
    fontSize: 12,
    fontWeight: "700",
  },
  itemPrice: {
    fontWeight: "800",
    color: "#a43b36",
  },
  qtyRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  qtyControl: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f1e7db",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ddcbb9",
  },
  qtyBtn: {
    width: 38,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  qtyBtnDisabled: {
    opacity: 0.35,
  },
  qtyBtnText: { fontSize: 18, fontWeight: "800", color: "#654332" },
  qtyValueBox: {
    minWidth: 36,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  qtyText: { fontSize: 16, fontWeight: "800", color: "#2c1b12" },
  removeLink: { paddingHorizontal: 6, paddingVertical: 4 },
  removeLinkText: { color: "#a43b36", fontWeight: "700" },
  summaryCard: {
    marginTop: 16,
    backgroundColor: "#fbf7f0",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e6d7c7",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    gap: 14,
  },
  totalRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  totalLabel: { fontSize: 16, fontWeight: "800", color: "#2c1b12" },
  totalValue: { fontSize: 20, fontWeight: "900", color: "#a43b36" },
  clearLink: { color: "#a43b36", fontWeight: "700", textDecorationLine: "underline" },
  checkoutBtn: {
    backgroundColor: "#b13c38",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  checkoutText: { color: "#fff", fontWeight: "800", fontSize: 16, letterSpacing: 0.4 },

  successState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    paddingHorizontal: 24,
  },
  successBadge: {
    width: 96,
    height: 96,
    borderRadius: 999,
    backgroundColor: "#21a45d",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 5,
    borderColor: "rgba(255,255,255,0.35)",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  successTitle: {
    fontSize: 27,
    fontWeight: "900",
    color: "#fdf8f0",
    textAlign: "center",
  },
  successSubtitle: {
    color: "#f2e8dc",
    fontSize: 14,
    textAlign: "center",
    marginTop: -4,
  },
  successCodeWrap: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    minWidth: 220,
    gap: 4,
  },
  successCodeLabel: {
    color: "#f7efe4",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  successCode: {
    fontSize: 26,
    fontWeight: "900",
    color: "#ffffff",
    marginBottom: 2,
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e6d7c7",
    padding: 16,
    gap: 10,
  },
  activeOrderIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 999,
    backgroundColor: "#b13c38",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#2c1b12",
  },
  modalText: {
    color: "#6e5a4b",
    fontSize: 13,
  },
  modalActions: {
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
    flexWrap: "wrap",
  },
  modalButton: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  modalGhostButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#d9cfc2",
  },
  modalPrimaryButton: {
    backgroundColor: "#b13c38",
  },
  modalGhostText: {
    color: "#6e5a4b",
    fontWeight: "700",
  },
  modalPrimaryText: {
    color: "#fff",
    fontWeight: "800",
  },
  disabledModalButton: {
    opacity: 0.6,
  },

  profileSummary: {
    borderWidth: 1,
    borderColor: "#eadfd2",
    backgroundColor: "#fbf7f0",
    borderRadius: 10,
    padding: 10,
    gap: 4,
  },
  profileSummaryText: {
    fontSize: 12,
    color: "#5f4b3c",
  },
  sectionLabel: {
    color: "#2c1b12",
    fontWeight: "800",
    fontSize: 13,
  },
  paymentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  paymentChip: {
    borderWidth: 1,
    borderColor: "#d9cfc2",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#fff",
  },
  paymentChipSelected: {
    backgroundColor: "#2c1b12",
    borderColor: "#2c1b12",
  },
  paymentChipText: {
    color: "#5f4b3c",
    fontWeight: "700",
    fontSize: 12,
  },
  paymentChipTextSelected: {
    color: "#fff",
  },
  notesInput: {
    borderWidth: 1,
    borderColor: "#d9cfc2",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fdfaf6",
    minHeight: 84,
    textAlignVertical: "top",
    color: "#2c1b12",
  },
});
